WebAppAssignmentDATABASE_5/Controllers/AjaxController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAssignmentDATABASE_5.Models;
using WebAppAssignmentDATABASE_5.Models.ViewModel;

namespace WebAppAssignmentDATABASE_5.Controllers
{
    public class AjaxController : Controller
    {
        IPeopleService _peopleService;

        public AjaxController(IPeopleService peopleService)
        {
            _peopleService = peopleService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            PeopleViewModel peopleViewModel = _peopleService.All();

            return View(peopleViewModel);
        }

        [HttpGet]
        public IActionResult PeoplePartial(int id)
        {
            return PartialView("PeoplePartial", _peopleService.All().PersonList);
        }

        [HttpPost]
        public IActionResult PersonPartial(int id)
        {
            Person p = _peopleService.Findby(id);

            return PartialView("PersonPartial", p);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            bool deleted = _peopleService.Remove(id);
            string result = "";

            if (deleted)
                result = "Successfully deleted!";
            else
                result = "Was not deleted!";

            return Content(result);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreatePersonViewModel createPersonViewModel)
        {
            if (ModelState.IsValid)
            {
                _peopleService.Add(createPersonViewModel);

                return RedirectToAction(nameof(PeoplePartial));
            }

            return View(createPersonViewModel);
        }
    }
}

WebAppAssignmentDATABASE_5/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebAppAssignmentDATABASE_5.Data;
using WebAppAssignmentDATABASE_5.Models;
using WebAppAssignmentDATABASE_5.Models.Service;
using WebAppAssignmentDATABASE_5.Models.ViewModel;

namespace WebAppAssignmentDATABASE_5.Controllers
{
    public class PeopleController : Controller
    {

        IPeopleService _peopleService;
        ICityService _cityService;
        PeopleDbContext _context;

        public PeopleController(IPeopleService peopleService, ICityService cityService, PeopleDbContext context)
        {
            _peopleService = peopleService;
            _cityService = cityService;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_peopleService.All());
        }

        [HttpPost]
        public IActionResult Index(PeopleViewModel peopleViewModel)
        {
            if (peopleViewModel.FilterText != null)
            {
                peopleViewModel = _peopleService.FindBy(peopleViewModel);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
            return View(peopleViewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreatePersonViewModel vm = new CreatePersonViewModel();
            vm.selectList = new SelectList(_context.Cities, "Name", "Name");

            return View(vm);
            //return View();
        }

        [HttpPost]
        public IActionResult Create(CreatePersonViewModel createPersonViewModel)
        {
            if (ModelState.IsValid)
            {
                Person person = _peopleService.Add(createPersonViewModel);

                int cityId = _context.Cities.Where(c => c.Name == createPersonViewModel.City).First().CityId;

                _cityService.AddPersonToCity(cityId, person);

                return RedirectToAction(nameof(Index));
            }

            createPersonViewModel.selectList = new SelectList(_context.Cities, "Name", "Name");
            return View(createPersonViewModel);
        }

        public IActionResult Remove(int id)
        {
            _peopleService.Remove(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

WebAppAssignmentDATABASE_5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_MCV_DataAssignments</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="headerContainer container">
                <a class="navbar-brand" asp-area="" asp-controller="People" asp-action="Index">Logo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse header">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ajax" asp-action="Index">Ajax</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="Bodycontainer container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <div>
        <footer>
            <span style="padding-left:240px">&#64;Ramya Talagavadi Kalegowda&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-primary" href="#">Back To Top</a></span>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>